//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfEntityMod.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class adherent
    {
        public int id { get; set; }
        public Nullable<int> idActivity { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string photo { get; set; }
    
        public virtual activity activity { get; set; }
    }
}
